//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncV1 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class UserSet : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserSet defaultInstance = ((UserSet)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSet())));
        
        public static UserSet Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".ubd")]
        public string UserDataExt {
            get {
                return ((string)(this["UserDataExt"]));
            }
            set {
                this["UserDataExt"] = value;
            }
        }
    }
}
